# -*- coding: utf-8 -*-
# action log message
ACTION_LOG_MESSAGE_REMIND = "REMIND"
ACTION_LOG_MESSAGE_CUSTOMER_CHAT = "CUSTOMER_CHAT"
ACTION_LOG_MESSAGE_UNASSIGN = "UNASSIGN"
ACTION_LOG_MESSAGE_ASSIGN = "ASSIGN"
ACTION_LOG_MESSAGE_COMPLETED = "COMPLETED"
ACTION_LOG_MESSAGE_REOPEN = "REOPEN"
ACTION_LOG_MESSAGE_NEW_INTERACTION = "NEW_INTERACTION"
ACTION_LOG_MESSAGE_FORWARDS = "FORWARDS"
