# -*- coding: utf-8 -*-


FACEBOOK_VERIFICATION_HUB_MODE = 'subscribe'
FACEBOOK_VERIFICATION_HUB_TOKEN = 'nhandd-super-secret-verification-code'


FACEBOOK_CONTACT_FIELDS = 'followers_count,fan_count'


FACEBOOK_MAX_SIZE_UPLOAD = 25600000

CHAT_TYPE_FACEBOOK_MAX_SIZE_UPLOAD = 25600000
CHAT_TYPE_FACEBOOK_MAX_IMAGE_SIZE_UPLOAD = 8388608