# Generated by Django 4.2.6 on 2023-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_user_is_noti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_noti',
            new_name='is_discord_noti',
        ),
        migrations.AddField(
            model_name='user',
            name='is_web_noti',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_workplace_noti',
            field=models.BooleanField(default=True),
        ),
    ]
