# Generated by Django 4.2.6 on 2023-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_is_noti_user_is_discord_noti_user_is_web_noti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='calendar_token',
            new_name='calendar_access_token',
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
